name: Deploy to VM

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Docker image tag"
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VM_IP }}
          username: ${{ secrets.VM_SSH_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            docker login cr.yandex -u json_key -p '${{ secrets.YC_KEY_JSON }}'
            docker pull cr.yandex/${{ secrets.YC_REGISTRY_ID }}/shri-infra:${{ github.event.inputs.version }}

            docker stop shri || true
            docker rm shri || true

            docker run -d --name shri -p 80:3000 cr.yandex/${{ secrets.YC_REGISTRY_ID }}/shri-infra:${{ github.event.inputs.version }}
