name: Deploy to VM

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        description: "Release version"

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ github.event.inputs.version }}

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker stop app || true
            docker rm app || true
            docker pull cr.yandex/${{ secrets.YANDEX_REGISTRY_ID }}/app:${{ env.VERSION }}_latest
            docker run -d --name app -p 80:3000 cr.yandex/${{ secrets.YANDEX_REGISTRY_ID }}/app:${{ env.VERSION }}_latest
