- name: Deploy to VM via SSH
  uses: appleboy/ssh-action@v1.0.0
  with:
    host: ${{ secrets.SERVER_IP }}
    username: ${{ secrets.SERVER_USER }}
    key: ${{ secrets.SERVER_SSH_KEY }}
    port: 22
    script: |
      echo '${{ secrets.YC_KEY_JSON }}' > key.json
      cat key.json | docker login cr.yandex --username json_key --password-stdin
      docker pull cr.yandex/${{ secrets.YC_REGISTRY_ID }}/app:${{ github.event.inputs.version }}_latest
      docker stop shri || true
      docker rm shri || true
      docker run -d --name shri -p 80:3000 cr.yandex/${{ secrets.YC_REGISTRY_ID }}/app:${{ github.event.inputs.version }}_latest
      rm key.json
