name: Deploy to VM

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        description: "Release version"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VM via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            echo '${{ secrets.YC_JSON_KEY }}' > key.json
            docker login cr.yandex/${{ secrets.YC_REGION }} -u json_key -p "$(cat key.json)"
            docker pull cr.yandex/${{ secrets.YC_REGION }}/${{ secrets.YC_REGISTRY_ID }}/app:${{ github.event.inputs.version }}_latest
            docker stop shri || true
            docker rm shri || true
            docker run -d --name shri -p 80:3000 cr.yandex/${{ secrets.YC_REGION }}/${{ secrets.YC_REGISTRY_ID }}/app:${{ github.event.inputs.version }}_latest
            rm key.json
