name: Release Fix

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: "Номер релиза (например: 7)"
        required: true

jobs:
  fix-release:
    runs-on: ubuntu-latest

    env:
      BASE_VERSION: ${{ github.event.inputs.release_version }}
      FIX_VERSION: fix${{ github.run_number }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - run: npm ci
      - run: npm run lint
      - run: npm test

      - name: Decode service account key
        run: echo "${{ secrets.YC_KEY_JSON }}" | base64 -d > key.json

      - name: Docker login to Yandex Container Registry
        run: docker login -u json_key -p "$(cat key.json)" cr.yandex

      - name: Build docker image
        run: |
          docker build -t cr.yandex/${{ secrets.YC_REGISTRY_ID }}/app:${{ env.BASE_VERSION }}_${{ env.FIX_VERSION }} .
          docker tag cr.yandex/${{ secrets.YC_REGISTRY_ID }}/app:${{ env.BASE_VERSION }}_${{ env.FIX_VERSION }} \
                     cr.yandex/${{ secrets.YC_REGISTRY_ID }}/app:${{ env.BASE_VERSION }}_latest

      - name: Push docker image
        run: |
          docker push cr.yandex/${{ secrets.YC_REGISTRY_ID }}/app:${{ env.BASE_VERSION }}_${{ env.FIX_VERSION }}
          docker push cr.yandex/${{ secrets.YC_REGISTRY_ID }}/app:${{ env.BASE_VERSION }}_latest

      - name: Create git tag
        run: |
          git tag v${{ env.BASE_VERSION }}_${{ env.FIX_VERSION }}
          git push origin v${{ env.BASE_VERSION }}_${{ env.FIX_VERSION }}

      - name: Post comment to release issue
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ env.BASE_VERSION }}
          body: |
            📦 **Релиз зафиксирован**
            - Версия: `${{ env.BASE_VERSION }}_${{ env.FIX_VERSION }}`
            - Автор: @${{ github.actor }}
            - Дата: ${{ github.event.head_commit.timestamp || github.run_started_at }}
            - Образ: `cr.yandex/${{ secrets.YC_REGISTRY_ID }}/app:${{ env.BASE_VERSION_
